### ISSUE TITLE
Quick demo

### ISSUE THREAD

**Issue by josephernest** [www-py/wwwpy#5]
Hi,

After reading your post on reddit, I (like many other people probably) would like to test it, quickly. 

My 2 cents: everyone sees many new projects each day, so few of us have 30 minutes to spend without first having a global idea ;)

TL;DR: Can you include a 2-minute install HOWTO in your README? It would allow people like me to do a quick test.

Just 10 lines would be enough :) And also some words about the general philosophy of the project in the README, aka "make me want to try your project" ;)

---

PS: also: why https://github.com/www-py/wwwpy? why one with hyphen and the other without? it hurts ;)

**Comment by simonegiacomelli** [comment]
Hey Joseph,

I just migrated this repo to https://github.com/wwwpy-labs/wwwpy

Btw, I also added some instructions on how to start. 
In a few days I will post on Reddit to inform people that wwwpy is now pip installable.

I hope to hear some of your feedback!

Btw, I looked some of your repos, you have impressive knowledge and skills!
