### ISSUE TITLE
Hot-reload, improve `server.rpc` support

### ISSUE THREAD

**Issue by simonegiacomelli** [www-py/wwwpy#6]
Currently the hot-reload is refreshing the server side code but it is not yet pushing the needed changes to the remote (browser).
What needs to be pushed are the changes to the functions arguments.
If one changes only the code behind the `server.rpc` code but keeps the functions definition unchanged, the hot-reload already works.

As a workaround you can refresh the browser page.

**Comment by www-py** [comment]
migrated to https://github.com/wwwpy-labs/wwwpy/issues/2
