### ISSUE TITLE
Execute/Schedule server side code

### ISSUE THREAD

**Issue by simonegiacomelli** [www-py/wwwpy#7]
We have the need to execute server code for multiple reasons:
* Notify the browser on some server-side triggered event. 
* Perform scheduled recurrent task(s) 
* Perform one-time task(s)

It would be easy to add a server side entry point but our primary goal here is to make it work well with hot-reload.

The following is how the browser `main` is defined.
```python
# remote/__init__.py 
async def main():
    import js
    # do something in the browser
```

What we want could be the counter-part on the server:
```python
# server/__init__.py
async def main():
    send_message_to_all_connected_browsers()
```

**Comment by www-py** [comment]
migrated to https://github.com/wwwpy-labs/wwwpy/issues/3
